---
title: "Assignment 1"
subtitle: "Data Analysis with Applications"
author: "이진우 20162299"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    highlight: pygments
  pdf_document: default
---

<br/>

### Metro Dataset (2019/11/01 - 2019/11/30)

<br/>

#### 1. 숭실대입구(살피재) 역의 11월 1일의 시간대별 승차 및 하차 인원 수를 하나의 그래프로 시각화해보자.

```{r message=FALSE}
# 사용할 패키지 추가
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggthemes)
library(tmaptools)
library(ggmap)
```

```{r graph1}
# 데이터파일 읽기
metro <- read.csv("metro.csv")
coord <- read.csv("metro_coord.csv")
str(metro)

# 텍스트 형태의 날짜를 Date 객체로 변환
metro$날짜 <- as.Date(metro$날짜)
str(metro)

# gather함수를 활용하여 시간대 별 승하차 데이터를 '시간대'열과 '인원수'열로 정리  ( metro2 ) 
metro2 <- metro %>% gather("X04...05","X05...06","X06...07","X07...08","X08...09",
                           "X09...10","X10...11","X11...12","X12...13","X13...14",
                           "X14...15","X15...16","X16...17","X17...18","X18...19",
                           "X19...20","X20...21","X21...22","X22...23","X23...24",
                           "X00...01","X01...02","X02...03","X03...04", key="시간대", value="인원수" )
str(metro2)

# 숭실대입구(살피재)역의 데이터만 추출  ( metro_ssu )
metro_ssu <- subset(metro2, 날짜=="2019-11-01" & 역명=="숭실대입구(살피재)")
str(metro_ssu)

# line plot 작성
ggplot(metro_ssu, aes(x=시간대, y=인원수, color=구분, group=구분)) + 
  geom_line(size=1) +
  geom_point(size=3) +
  scale_y_continuous(breaks=seq(0,3000,500)) +
  theme(axis.text.x=element_text(angle=30, hjust=1)) +
  labs(title="1.  숭실대입구(살피재) 역의 11월 1일의 시간대별 승차 및 하차 인원 수")
```



<br/>


#### 2. 숭실대입구(살피재) 역의 11월 4일(월)부터 11월10일(일)까지 
#### 일주일간 각 요일별 시간대별 승차인원과 하차인원의 분포를 각각 heat map으로 시각화해보자.

```{r graph2}
# 주어진 기간에서 숭실대입구(살피재)역의 승차 데이터만 추출  ( metro_ssu2_a )
metro_ssu2_a <- subset(metro2, 역명=="숭실대입구(살피재)" & 날짜>="2019-11-04" & 날짜<="2019-11-10" & 구분=="승차")
str(metro_ssu2_a)

# 승차 Heat map 작성, scale_x_date(date_labels="%A)로 날짜데이터를 요일로 표시
ggplot(data = metro_ssu2_a, aes(x=시간대, y=날짜, fill=인원수)) +
  geom_tile(alpha=1) +
  scale_fill_gradient(low="white", high="orange") +
  scale_y_date(date_labels="%A", breaks=metro_ssu2_a$날짜) +
  theme(axis.text.x=element_text(angle=30, hjust=1)) +
  labs(title="2_a.  11/4 ~ 11/10 숭실대입구(살피재)역의 요일별 시간대별 승차 인원 수", x="시간대", y="요일")


# 주어진 기간의 숭실대입구(살피재)역에서의 하차 데이터만 추출  ( metro_ssu2_b )
metro_ssu2_b <- subset(metro2, 역명=="숭실대입구(살피재)" & 날짜>="2019-11-04" & 날짜<="2019-11-10" & 구분=="하차")
str(metro_ssu2_b)

# 하차 Heat map 작성, scale_x_date(date_labels="%A)로 날짜데이터를 요일로 표시
ggplot(data = metro_ssu2_b, aes(x=시간대, y=날짜, fill=인원수)) +
  geom_tile(alpha=1) +
  scale_fill_gradient(low="white", high="green") +
  scale_y_date(date_labels="%A", breaks=metro_ssu2_b$날짜) +
  theme(axis.text.x=element_text(angle=30, hjust=1)) +
  labs(title="2_b.  11/4 ~ 11/10 숭실대입구(살피재)역의 요일별 시간대별 하차 인원 수", x="시간대", y="요일")
```



<br/>


#### 3. 7호선의 모든 역 중에서 유동인구(월간 승하차 전체인원)가 가장 많은 20개 역에 대한 유동인구 수를 그래프로 시각화해보자.

```{r graph3}
# 7호선의 데이터만 추출 ( metro_line7 )
metro_line7 <- subset(metro2, 호선=="7호선")
str(metro_line7)

# 역명을 기준으로 인원수의 합계를 구하여 각 역의 유동인구 계산 ( metro_line7_agg )
metro_line7_agg <-aggregate(metro_line7$인원수, by=list(metro_line7$역명), sum)
str(metro_line7_agg)

# 데이터프레임을 인원 수에 따라 내림차순 정렬, metro_line7_agg에서 유동인구 열의 이름이 x  ( metro_line7_agg_orderd )
metro_line7_agg_ordered <- arrange(metro_line7_agg, -x)
str(metro_line7_agg_ordered)

# 유동인구 상위 20개의 데이터 추출  ( metro_line7_agg_20 )
metro_line7_agg_20 <- metro_line7_agg_ordered[1:20,] 
str(metro_line7_agg_20)

# bar chart 작성
ggplot(metro_line7_agg_20, aes(x=reorder(Group.1,x), y=x)) +
  geom_bar(stat="identity") +
  geom_text(aes(label=x), hjust=-0.1) +
  coord_flip() +
  scale_y_continuous(breaks=c(seq(0,3000000,500000)), limits=c(0,2700000)) +
  labs(title="3.  7호선 유동인구 상위 20개 역의 유동인구 수", x="유동인구 수", y="역명")
```



<br/>


#### 4. 7호선 지하철역 위치 정보를 활용하여 7호선의 모든 역에 대한 유동인구 분포를 지도 위에 시각화해보자.
#### 크기, 투명도 등을 활용하여 분포를 표현할 수 있다.

```{r graph4}
# 7호선 역의 유동인구와 위치 데이터프레임 생성  ( metro_line7_agg_coord )
metro_line7_agg_coord <- data.frame(역명=metro_line7_agg$Group.1, 유동인구=metro_line7_agg$x, lat=coord$lat, lon=coord$lon) 
str(metro_line7_agg_coord)

# 필요한 지도의 데이터를 역 위치 데이터에서 추출
map_coord <- c(left=min(metro_line7_agg_coord$lon)-0.02, bottom=min(metro_line7_agg_coord$lat)-0.02,
               right=max(metro_line7_agg_coord$lon)+0.02, top=max(metro_line7_agg_coord$lat)+0.02)

# 지도 불러오기
metro_map <- get_stamenmap(bbox=map_coord, zoom=11, maptype="terrain")

# 불러온 지도에 점의 투명도와 크기로 유동인구 분포를 시각화
ggmap(metro_map, base_layer = ggplot(data = metro_line7_agg_coord, aes(x=lon, y=lat, color=유동인구, size=유동인구))) +
  geom_point(alpha=0.8) +
  labs(title="4.  7호선 모든 역에 대한 유동인구 분포")
```



